name: output-a-dynamic-matrix

'on':
  pull_request:
    paths:
      - terraform/workloads/**
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  detect-changed-workloads:
    runs-on: ubuntu-latest
    outputs:
      workloads-json: '${{ steps.changed.outputs.workloads-json }}'
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine changed workloads
        id: changed
        run: |
          set -euo pipefail

          EVENT_NAME="${{ github.event_name }}"
          if [ "$EVENT_NAME" = "pull_request" ]; then
            BASE_REF="${{ github.event.pull_request.base.sha }}"
            git fetch origin "$BASE_REF"
          elif [ "$EVENT_NAME" = "push" ]; then
            BASE_REF="$(git rev-parse HEAD^)"
          else
            git fetch origin main
            BASE_REF="FETCH_HEAD"
          fi

          echo "Using base ref: $BASE_REF"

          WORKLOADS=$(git diff --name-only "${BASE_REF}...HEAD" \
            | grep '^terraform/workloads/' \
            | cut -d/ -f3 \
            | sort -u \
            | jq -R -s -c 'split("\n") | map(select(length>0))'
          )

          echo "Detected workloads: $WORKLOADS"
          echo "workloads-json=$WORKLOADS" >> "$GITHUB_OUTPUT"

  build-matrix:
    needs: detect-changed-workloads
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
    steps:
      - name: Build matrix with secret names
        id: build
        run: |
          echo "Generating matrix from workloads..."
          workloads='${{ needs.detect-changed-workloads.outputs.workloads-json }}'
          matrix=$(echo "$workloads" | jq -c 'map({workload: ., secret_name: (ascii_upcase | gsub("ACCOUNT_"; "") | "ACCOUNT_" + (. | split("_")[-1]))})')
          echo "Generated matrix: $matrix"
          echo "matrix={\"include\":$matrix}" >> "$GITHUB_OUTPUT"

  use-matrix:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    env:
      ACCOUNT_1: ${{ secrets.ACCOUNT_1 }}
      ACCOUNT_2: ${{ secrets.ACCOUNT_2 }}
      ACCOUNT_3: ${{ secrets.ACCOUNT_3 }}
      ACCOUNT_4: ${{ secrets.ACCOUNT_4 }}
    steps:
      - name: Say hello
        run: |
          echo "Hello from ${{ matrix.workload }}"
          echo "I'm going to leak the ${{ matrix.secret_name }} secret value: ${{ secrets[matrix.secret_name] }}"
