name: output-a-dynamic-matrix

'on':
  pull_request:
    paths:
      - terraform/workloads/**
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  detect-changed-workloads:
    runs-on: ubuntu-latest
    outputs:
      workloads-json: '${{ steps.changed.outputs.workloads-json }}'
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine changed workloads
        id: changed
        run: |
          set -euo pipefail

          EVENT_NAME="${{ github.event_name }}"
          if [ "$EVENT_NAME" = "pull_request" ]; then
            BASE_REF="${{ github.event.pull_request.base.sha }}"
            git fetch origin "$BASE_REF"
          elif [ "$EVENT_NAME" = "push" ]; then
            BASE_REF="$(git rev-parse HEAD^)"
          else
            git fetch origin main
            BASE_REF="FETCH_HEAD"
          fi

          echo "Using base ref: $BASE_REF"

          WORKLOADS=$(git diff --name-only "${BASE_REF}...HEAD" \
            | grep '^terraform/workloads/' \
            | cut -d/ -f3 \
            | sort -u \
            | jq -R -s -c 'split("\n") | map(select(length>0))'
          )

          echo "Detected workloads: $WORKLOADS"
          echo "workloads-json=$WORKLOADS" >> "$GITHUB_OUTPUT"

  use-matrix:
    needs: detect-changed-workloads
    if: needs.detect-changed-workloads.outputs.workloads-json != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workload: ${{ fromJson(needs.detect-changed-workloads.outputs.workloads-json) }}
    steps:
      - name: Determine account ID from workload
        id: set-account
        run: |
          case "${{ matrix.workload }}" in
            account_1) echo "account_id=${{ secrets.ACCOUNT_1 }}" >> "$GITHUB_OUTPUT" ;;
            account_2) echo "account_id=${{ secrets.ACCOUNT_2 }}" >> "$GITHUB_OUTPUT" ;;
            account_3) echo "account_id=${{ secrets.ACCOUNT_3 }}" >> "$GITHUB_OUTPUT" ;;
            account_4) echo "account_id=${{ secrets.ACCOUNT_4 }}" >> "$GITHUB_OUTPUT" ;;
            *) echo "Unknown workload: ${{ matrix.workload }}"; exit 1 ;;
          esac
      - name: Say hello
        run: |
          echo "Hello from ${{ matrix.workload }}"
          echo "I'm going to leak this secret value: $ACCOUNT_ID"
